"""Compatibility facade for the data layer.

The project imports `models` widely, so this module re-exports the public API
from smaller thematic modules while keeping the import surface stable.
"""

from db import get_db
from model_auth import (
    LOGIN_CLEANUP_MINUTES,
    LOGIN_WINDOW_MINUTES,
    MAX_LOGIN_ATTEMPTS,
    activate_lawyer,
    change_lawyer_password,
    change_password,
    cleanup_old_attempts,
    clear_login_attempts,
    create_lawyer,
    deactivate_lawyer,
    get_all_lawyers,
    get_lawyer_by_id,
    get_lawyer_by_username,
    is_rate_limited,
    lawyer_must_change_password,
    must_change_password,
    record_login_attempt,
    reset_lawyer_password,
    verify_lawyer_password,
    verify_password,
)
from model_balance import check_onchain_balance, recalculate_raised_btc
from model_config import (
    SETTINGS_DECIMAL_FIELDS,
    SETTINGS_INTEGER_FIELDS,
    SETTINGS_TEXT_FIELDS,
    SETTINGS_URL_FIELDS,
    get_all_config,
    get_config,
    get_localized_config,
    set_config,
    validate_settings_form,
)
from model_content import (
    add_media_link,
    approve_article,
    clear_article_approvals,
    create_article,
    delete_article,
    delete_media_link,
    get_article_approvals,
    get_article_by_id,
    get_article_by_slug,
    get_article_for_lang,
    get_articles,
    get_articles_for_lang,
    get_media_links,
    publish_article_with_approval,
    revoke_approval,
    unpublish_article,
    update_article,
)
from model_profile import (
    VALID_CATEGORIES,
    add_profile_link,
    delete_profile_link,
    get_featured_profile_links,
    get_profile_link_by_id,
    get_profile_links,
    get_profile_links_grouped,
    update_profile_link,
)

__all__ = [
    "LOGIN_CLEANUP_MINUTES",
    "LOGIN_WINDOW_MINUTES",
    "MAX_LOGIN_ATTEMPTS",
    "SETTINGS_DECIMAL_FIELDS",
    "SETTINGS_INTEGER_FIELDS",
    "SETTINGS_TEXT_FIELDS",
    "SETTINGS_URL_FIELDS",
    "activate_lawyer",
    "add_media_link",
    "add_profile_link",
    "approve_article",
    "change_lawyer_password",
    "change_password",
    "check_onchain_balance",
    "cleanup_old_attempts",
    "clear_article_approvals",
    "clear_login_attempts",
    "create_article",
    "create_lawyer",
    "deactivate_lawyer",
    "delete_article",
    "delete_media_link",
    "get_all_config",
    "get_all_lawyers",
    "get_article_approvals",
    "get_article_by_id",
    "get_article_by_slug",
    "get_article_for_lang",
    "get_articles",
    "get_articles_for_lang",
    "get_config",
    "get_db",
    "get_featured_profile_links",
    "get_lawyer_by_id",
    "get_lawyer_by_username",
    "get_media_links",
    "get_localized_config",
    "get_profile_link_by_id",
    "get_profile_links",
    "get_profile_links_grouped",
    "is_rate_limited",
    "lawyer_must_change_password",
    "must_change_password",
    "publish_article_with_approval",
    "recalculate_raised_btc",
    "record_login_attempt",
    "reset_lawyer_password",
    "revoke_approval",
    "set_config",
    "unpublish_article",
    "update_profile_link",
    "update_article",
    "validate_settings_form",
    "VALID_CATEGORIES",
    "verify_lawyer_password",
    "verify_password",
]
